pygments:     true
permalinks: pretty
relative_permalinks: false
languages:
    - name: 'English'
      key: 'en'
    - name: 'Español'
      key: 'es'
    - name: '中文'
      key: 'cn'
port:         4478

# If running locally, simply comment out the line below to make all urls relative

#url:          http://docs.ghost.org